theme: jekyll-theme-cayman

title: Chroniques Oubliées du BeauBarbu
short_title: COBB
description: Idées pour COF, COC, COG etc, finies... ou pas

plugins:
    - jekyll-menus

sass:
    sass_dir: _sass

baseurl: "/chroniques"
collections:
    profils:
        output: true
        permalink: /:categories/profils/:name

defaults:
    - scope:
          path: ""
          type: "profils"
      values:
          layout: "profil"
    - scope:
          path: ""
      values:
          layout: "default"
